kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang
    commands:
      - go test -v ./...
      - go build
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dashotv/tower
      tags:
        - latest
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - host.docker.internal
      port: 22
      username: deploy
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - sudo echo "Hello World"

trigger:
  branch:
    - main
  event:
    - push
