kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang
    commands:
      - go test -v ./...
      - go build
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dashotv/tower
      tags:
        - latest
trigger:
  branch:
    - main
  event:
    - push
