mode: release
port: 9000
cron: true
connections:
  default:
    uri: mongodb://dashotv-db-1:27017
    database: database
  medium:
    database: seer_development
    collection: media
  download:
    database: seer_development
    collection: downloads
  series:
    database: seer_development
    collection: media
  episode:
    database: seer_development
    collection: media
  release:
    database: torch_development
    collection: torrents
  watch:
    database: seer_development
    collection: watches

