mode: release
port: 9000
cron: true
auth: false
filesystems:
  enabled: false
  directories:
    - /media/anime
    - /media/ecchi
    - /media/kids
    - /media/movies
    - /media/movies3d
    - /media/movies4k
    - /media/tv
redis:
  address: redis:6379
connections:
  default:
    uri: mongodb://dashotv-db-1:27017
    database: database
  medium:
    database: seer_development
    collection: media
  download:
    database: seer_development
    collection: downloads
  series:
    database: seer_development
    collection: media
  episode:
    database: seer_development
    collection: media
  movie:
    database: seer_development
    collection: media
  release:
    database: torch_development
    collection: torrents
  feed:
    database: torch_development
    collection: feeds
  watch:
    database: seer_development
    collection: watches
  pin:
    database: tower_development
    collection: pins
