mode: release
port: 9000

connections:
  default:
    uri: mongodb://host.docker.internal:27017
    database: database
  medium:
    database: seer_development
    collection: media
  download:
    database: seer_development
    collection: downloads
  release:
    database: torch_development
    collection: torrents
