mode: release
logger: dev
port: 9000
cron: true
auth: false
plex: http://localhost:9000/plex # external plex proxied url
minion:
  concurrency: 5
Nats:
  URL: nats://localhost:4222
tmdb:
  images: https://image.tmdb.org/t/p/original
directories:
  images: /images
redis:
  address: redis:6379
connections:
  default:
    uri: mongodb://localhost:27017
    database: database
  minion:
    uri: mongodb://localhost:27017
    database: minion
    collection: jobs
  medium:
    database: seer_development
    collection: media
  download:
    database: seer_development
    collection: downloads
  series:
    database: seer_development
    collection: media
  episode:
    database: seer_development
    collection: media
  movie:
    database: seer_development
    collection: media
  release:
    database: torch_development
    collection: torrents
  feed:
    database: torch_development
    collection: feeds
  watch:
    database: seer_development
    collection: watches
  pin:
    database: tower_development
    collection: pins
  user:
    database: tower_development
    collection: users
  request:
    database: tower_development
    collection: requests
  message:
    database: tower_development
    collection: messages
  minion_job:
    database: tower_development
    collection: minion_jobs
