// This file is autogenerated by Golem
// Do NOT make modifications, they will be lost
package server

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/dashotv/tower/server/downloads"
	"github.com/dashotv/tower/server/movies"
	"github.com/dashotv/tower/server/releases"
	"github.com/dashotv/tower/server/series"
	"github.com/dashotv/tower/server/upcoming"
)

func (s *Server) Routes() {
	s.Router.GET("/", homeHandler)

	downloads.Routes()
	movies.Routes()
	releases.Routes()
	series.Routes()
	upcoming.Routes()

}

func homeHandler(c *gin.Context) {
	Home(c)
}

func Home(c *gin.Context) {
	c.String(http.StatusOK, "home")
}
