// This file is autogenerated by Golem
// Do NOT make modifications, they will be lost
package series

import (
	"github.com/gin-gonic/gin"

	"github.com/dashotv/tower/application"
	"github.com/dashotv/tower/config"
)

var cfg *config.Config
var app *application.App

func Routes() {
	cfg = config.Instance()
	app = application.Instance()

	r := app.Router.Group("/series")
	r.GET("/", indexHandler)
	r.POST("/", createHandler)
	r.GET("/:id", showHandler)
	r.PUT("/:id", updateHandler)
	r.DELETE("/:id", deleteHandler)
}

func indexHandler(c *gin.Context) {
	Index(c)
}

func createHandler(c *gin.Context) {
	Create(c)
}

func showHandler(c *gin.Context) {
	id := c.Param("id")
	Show(c, id)
}

func updateHandler(c *gin.Context) {
	id := c.Param("id")
	Update(c, id)
}

func deleteHandler(c *gin.Context) {
	id := c.Param("id")
	Delete(c, id)
}
