name: tower
repo: github.com/dashotv/tower
groups:
  downloads:
    path: /downloads
    rest: true
  series:
    path: /series
    rest: true
  movies:
    path: /movies
    rest: true
  releases:
    path: /releases
    rest: true
