name: tower
repo: github.com/dashotv/tower
groups:
  downloads:
    path: /downloads
    routes:
      index:
        path: /
      create:
        method: POST
        path: /
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        method: PUT
        path: /:id
        params:
          - name: id
            type: string
      setting:
        method: PATCH
        path: /:id
        params:
          - name: id
            type: string
      delete:
        method: DELETE
        path: /:id
        params:
          - name: id
            type: string
      recent:
        path: /recent
      medium:
        path: /:id/medium
        params:
          - name: id
            type: string
      select:
        method: PUT
        path: /:id/select
        params:
          - name: id
            type: string
  upcoming:
    path: /upcoming
    routes:
      index:
        path: /
  episodes:
    path: /episodes
    routes:
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  series:
    path: /series
    routes:
      index:
        path: /
      create:
        method: POST
        path: /
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        method: PUT
        path: /:id
        params:
          - name: id
            type: string
      setting:
        method: PATCH
        path: /:id
        params:
          - name: id
            type: string
      delete:
        method: DELETE
        path: /:id
        params:
          - name: id
            type: string
      seasons:
        path: /:id/seasons
        params:
          - name: id
            type: string
      seasonEpisodesAll:
        path: /:id/seasons/all
        params:
          - name: id
            type: string
      seasonEpisodes:
        path: /:id/seasons/:season
        params:
          - name: id
            type: string
          - name: season
            type: string
      currentSeason:
        path: /:id/currentseason
        params:
          - name: id
            type: string
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
      watches:
        path: /:id/watches
        params:
          - name: id
            type: string
  movies:
    path: /movies
    routes:
      index:
        path: /
      create:
        method: POST
        path: /
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        method: PUT
        path: /:id
        params:
          - name: id
            type: string
      setting:
        method: PATCH
        path: /:id
        params:
          - name: id
            type: string
      delete:
        method: DELETE
        path: /:id
        params:
          - name: id
            type: string
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
  releases:
    path: /releases
    rest: true
  feeds:
    path: /feeds
    rest: true
