repo: github.com/dashotv/tower
name: tower
groups:
  downloads:
    path: /downloads
    routes:
      create:
        path: /
        method: POST
      delete:
        path: /:id
        method: DELETE
        params:
          - name: id
            type: string
      index:
        path: /
      last:
        name: last
        path: /last
      medium:
        path: /:id/medium
        params:
          - name: id
            type: string
      recent:
        path: /recent
      select:
        path: /:id/select
        method: PUT
        params:
          - name: id
            type: string
      setting:
        path: /:id
        method: PATCH
        params:
          - name: id
            type: string
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  episodes:
    path: /episodes
    routes:
      setting:
        path: /:id
        method: PATCH
        params:
          - name: id
            type: string
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  feeds:
    path: /feeds
    rest: true
  jobs:
    name: jobs
    path: /jobs
    routes:
      index:
        name: index
        path: /
  movies:
    path: /movies
    routes:
      create:
        path: /
        method: POST
      delete:
        path: /:id
        method: DELETE
        params:
          - name: id
            type: string
      index:
        path: /
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
      setting:
        path: /:id
        method: PATCH
        params:
          - name: id
            type: string
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  plex:
    name: plex
    path: /plex
    routes:
      auth:
        name: auth
        path: /auth
      index:
        name: index
        path: /index
      update:
        name: update
        path: /update
  releases:
    path: /releases
    routes:
      create:
        path: /
        method: POST
      delete:
        path: /:id
        method: DELETE
        params:
          - name: id
            type: string
      index:
        path: /
      popular:
        name: popular
        path: /popular/:interval
        params:
          - name: interval
            type: string
      setting:
        path: /:id
        method: PATCH
        params:
          - name: id
            type: string
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  series:
    path: /series
    routes:
      create:
        path: /
        method: POST
      currentSeason:
        path: /:id/currentseason
        params:
          - name: id
            type: string
      delete:
        path: /:id
        method: DELETE
        params:
          - name: id
            type: string
      index:
        path: /
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
      seasonEpisodes:
        path: /:id/seasons/:season
        params:
          - name: id
            type: string
          - name: season
            type: string
      seasonEpisodesAll:
        path: /:id/seasons/all
        params:
          - name: id
            type: string
      seasons:
        path: /:id/seasons
        params:
          - name: id
            type: string
      setting:
        path: /:id
        method: PATCH
        params:
          - name: id
            type: string
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
      watches:
        path: /:id/watches
        params:
          - name: id
            type: string
  upcoming:
    path: /upcoming
    routes:
      index:
        path: /
