name: tower
repo: github.com/dashotv/tower
groups:
  downloads:
    path: /downloads
    rest: true
  upcoming:
    path: /upcoming
    routes:
      index:
        path: /
  episodes:
    path: /episodes
    routes:
      update:
        path: /:id
        method: PUT
        params:
          - name: id
            type: string
  series:
    path: /series
    routes:
      index:
        path: /
      create:
        method: POST
        path: /
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        method: PUT
        path: /:id
        params:
          - name: id
            type: string
      delete:
        method: DELETE
        path: /:id
        params:
          - name: id
            type: string
      seasons:
        path: /:id/seasons
        params:
          - name: id
            type: string
      seasonEpisodes:
        path: /:id/seasons/:season
        params:
          - name: id
            type: string
          - name: season
            type: string
      currentSeason:
        path: /:id/currentseason
        params:
          - name: id
            type: string
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
  movies:
    path: /movies
    routes:
      index:
        path: /
      create:
        method: POST
        path: /
      show:
        path: /:id
        params:
          - name: id
            type: string
      update:
        method: PUT
        path: /:id
        params:
          - name: id
            type: string
      delete:
        method: DELETE
        path: /:id
        params:
          - name: id
            type: string
      paths:
        path: /:id/paths
        params:
          - name: id
            type: string
  releases:
    path: /releases
    rest: true
