name: config
path: /config
routes:
  - name: settings
    path: /:id
    method: PATCH
    result: "*Setting"
    params:
      - name: id
        type: string
      - name: settings
        type: "*Setting"
        bind: true
